### PR TITLE
Play travis

### PR DESCRIPTION
**Pull request by Andreyovs**
https://github.com/Andreyovs

### CODE REVIEW

**Review by hostberg — CHANGES_REQUESTED** [review]
Проверки Travis CI должны быть пройдены и не забывай про label'ы.

**Comment by Andreyovs** [comment]
Не пойму в чем ошибка The command "curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh | bash" failed and exited with 1 during

**Comment by hostberg** [comment]
======================================================================
FAIL: test_equal (test.NumbersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/play-travis/test.py", line 6, in test_equal
    self.assertEqual(1 + 1, 1)
AssertionError: 2 != 1
----------------------------------------------------------------------
Ran 1 test in 0.000s
FAILED (failures=1)

Нужно поправить скрипт.

**Comment by Andreyovs** [comment]
fixed

**Comment by hostberg** [comment]
Работа принята. 👍

**Review by hostberg — APPROVED** [review]

**Pull request merged**
